### ISSUE TITLE
hidraw and Info class error

### ISSUE THREAD

**Issue by jpmeijers** [lluisball/godenerg#3]
```
jpmeijers@laptop:~/Homebug/godenerg$ python3 axpert/main.py --usb -d /dev/hidraw0 --status
Traceback (most recent call last):
  File "axpert/main.py", line 357, in <module>
    run_cmd(args)
  File "axpert/main.py", line 57, in run_cmd
    Connector = resolve_connector(args)
  File "/home/jpmeijers/Homebug/godenerg/axpert/connector.py", line 45, in resolve_connector
    module = import_module(module_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jpmeijers/Homebug/godenerg/axpert/connector_usbhid.py", line 1, in <module>
    import hidraw
ModuleNotFoundError: No module named 'hidraw'
```

Then I installed hidraw using pip3
`sudo pip3 install hidraw`

Now I get:
```
jpmeijers@laptop:~/Homebug/godenerg$ python3 axpert/main.py --usb -d /dev/hidraw0 --status
Traceback (most recent call last):
  File "axpert/main.py", line 357, in <module>
    run_cmd(args)
  File "axpert/main.py", line 57, in run_cmd
    Connector = resolve_connector(args)
  File "/home/jpmeijers/Homebug/godenerg/axpert/connector.py", line 45, in resolve_connector
    module = import_module(module_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jpmeijers/Homebug/godenerg/axpert/connector_usbhid.py", line 1, in <module>
    import hidraw
  File "/usr/local/lib/python3.6/dist-packages/hidraw/__init__.py", line 6, in <module>
    from hidraw import Info
ImportError: cannot import name 'Info'

```

Am I installing the correct hidraw package that is necessary for this software?

**Comment by xxlvoyager** [comment]
#Rewrite connector_usbhid.py
import os
from connector import (Connector)
from time import sleep

class USBConnector(Connector):

    def write(self, data):    
        os.write (self.fd, data)
        sleep(0.45)

    def read(self, size):
        retry=0
        return self._read(size)

    def _read(self, size):
        data = ''
        while True:
            sleep(0.17)
            data += ''.join(map(chr, os.read (self.fd,size)))
            if not data or '\r' in data or len(data) >= size:
                break
        return data
  

    def open(self):
        try:
            self.fd = os.open('/dev/hidraw0', os.O_RDWR | os.O_NONBLOCK)
            sleep(0.35)
        except Exception as e:
            self.log.error(e)

        
    def close(self):        
        os.close(self.fd)
